# Generated by Django 4.2 on 2023-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='type',
            field=models.CharField(choices=[('exact', 'Exact'), ('range', 'Range')], default='exact', max_length=10),
        ),
    ]
