# Generated by Django 4.2 on 2023-05-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0002_vacancy_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
